export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';

export const FETCH_ASSET = 'FETCH_ASSET';
export const FETCH_ASSETS = 'FETCH_ASSETS';
export const CREATE_ASSET = 'CREATE_ASSET';
export const DELETE_ASSET = 'DELETE_ASSET';
export const EDIT_ASSET = 'EDIT_ASSET';

export const ASSET_ERROR = 'ASSET_ERROR';